export const FETCH_TODOS = "FETCH_TODOS";

export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_INPUT_ERROR_TRUE = "SET_INPUT_ERROR_TRUE";
export const SET_INPUT_ERROR_FALSE = "SET_INPUT_ERROR_FALSE";
export const DELETE_TODO = "DELETE_TODO";
